name: dev_env
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - matplotlib-base
  - numpy
  - jupyterlab
  - openpyxl=3.1.2
  - nltk
  - scikit-learn
  - moviepy
  - pydub
  - gensim
  - spacy
  - sentence-transformers