name: dvlog_env_test
channels:
  - anaconda
  - conda-forge
  - defaults
  - pytorch
  - nvidia
dependencies:
  - python=3.11
  - pandas=2.2.0
  - numpy
  - openpyxl=3.1.2
  - pytorch=2.2.0
  - torchvision=0.17.0
  - torchaudio=2.2.0
  - pytorch-cuda=11.8
  - scikit-learn
  - confection
  - typer
